### ISSUE TITLE
Wound tolerance calculation error

### ISSUE THREAD

**Issue by PhyDoesStuff** [StasTserk/foundry-burningwheel#169]
Wound tolerances are incorrectly calculated when Mortal Wounds is Grey. Superficial should be B ${forte}, Light should be B ${forte x2}, Traumatic is one left of Mortal, Severe one left of Traumatic, and Midi is two left of Severe (see BW Gold Revised p546, Heroic Mortal Wound). This could push Traumatic, Severe, and/or Midi back down to Black shade if MW's exponent is low enough, based on how the PTGS functions (see BW Gold Revised p484, Shade). Huzzah for base-16 health tracks, I guess?

It also stands to reason that White MW would follow the same logic using G forte and G forte*2 for Su and Li, respectively.

For NPC sheets, the easiest solution is to make the Shade for each tolerance a drop-down that can be changed, since Thresholds are otherwise already manually set.

Since PC sheetss have the PTGS, it's a bit more difficult. A possible solution would be to present the full PTGS (either as a Black row, then a Gray row, then a White row; or as a single horizontally-scrollable view) while applying MW thresholds appropriately.

**Comment by StasTserk** [comment]
So, after all the juggling between issues, I'm ready to close this particular issue with a fix for the NPC side of heroic wound tolerance. It's not clear to me that there is an elegant solution for displaying a PTGS that might span multiple shades, having 16 columns including 5 input fields per, as well as backing data is already kind of a clumsy thing to render and track in the actor's backing data.

There is a work around with PC mortal wounds in that the dropdowns on the PTGS are still configurable, even if the automatic calculation isn't entirely accurate. This kind of scenario is the reason why the PTGS area has a refresh button rather than having the tolerance be recalculated each time.

I'm going to split off the problem of PC wounds into a separate issue that is open for discussion of that specific implementation hurdle.
