### ISSUE TITLE
Training Skills potentially not showing up under training skills

### ISSUE THREAD

**Issue by coreyhickson** [StasTserk/foundry-burningwheel#291]
**Describe the bug**
I might be misusing the character sheet, but when I add a training skill to the character sheet, they're not showing up under Training Skills but are showing up as rollable skills under the skills:

**To Reproduce**
1. Start a character sheet
1. Add a training skill
1. Look under the weapons and armor section

**Expected behavior**
I believe I should be able to see the training skills under the training skills header under Weapons and Armor

**Screenshots**
![image](https://user-images.githubusercontent.com/19170294/102161234-8bdec080-3e4c-11eb-88c8-a132c765c47a.png)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser: Desktop app
 - Version Latest version on December 14th, 2020

**Additional context**

**Comment by StasTserk** [comment]
You are not misusing the sheet. This is sort of my bad since the option for training skills as a skill type is rather incorrect. I added it very early on in the sheet's development and have more or less forgotten about it.

Technically skills like shield and armor training fall under the martial skill type and the sheet accounts for that correctly.

I think for minimal disruption for things people have already done though I'll ensure that any skills with the training type also end up in that list of non-rollable skills.

**Comment by coreyhickson** [comment]
Awesome, I can change that on my end as well. Thank you!
