### ISSUE TITLE
Modules with data and the future of ruleset

### ISSUE THREAD

**Issue by Nivroc** [StasTserk/foundry-burningwheel#314]
Hey, currently enjoying the ruleset, but I weren't able to find any Lifepaths or Skills inside the ruleset itself. 
I saw there were issues some time ago about this and wanted to catch up.
Are there any compendiums available? Do you need any help creating them?

Also wanted to ask about the future of the ruleset. You stated in the release that all of the features are now implemented.
I do have some input on several features that would be really convenient to have(like stance tracking for Fight!). Should I create issues/PRs - what's your view on further developement?

**Comment by StasTserk** [comment]
On the topic of adding compendiums, this isn't something that is currently possible to include in the system since it very much would infringe upon the IP of the creators of the game. There is perhaps an opportunity to work with BWHQ in the future to release official "premium" content for the system (and some systems in foundry have already gone this route) but there haven't been any steps taken in that direction.

As for accepting new features there are a few options.
 - Opening a PR is one way. Subject to review on my part, of course.
 - Forking the system and not opening a PR.
 - Creating a Foundry module that modifies the system.

Personally, at the moment I have no plans to start big new features, though fixing bugs is something I definitely plan to keep up on. I do plan on writing up a `CONTRIBUTING.md` some time this week to make some guidelines for contribution.

**Comment by Nivroc** [comment]
As far as I know Luke Crane doesn't want for any of his games to be digitalised in any way so probably that means sticking to http://charred-black.herokuapp.com/#/ for character burning at least. Imports from there could be a huge QOL improvement.

**Comment by StasTserk** [comment]
For something like a charred black importer, I'm certainly not planning to add it into the system. If you are interested in something like that for your own game, writing a module or forking the system would be the way to go.
