### ISSUE TITLE
Many roll types no longer work after update to v10

### ISSUE THREAD

**Issue by BBBNBBB** [StasTserk/foundry-burningwheel#392]
**Describe the bug**
When trying to make certain tests (listed below), after "Roll" has been clicked on the difficulty dialogue, no results appear in the chat and errors are created in the console.

The rolls that do not work are:
1. Relationships
2. Stats
3. Attributes
4. Tax on Spells

Shrug it off and Grit Your Teeth are special as they produce errors similar to the above, but they produce rolls as normal in the chat. After rolling with one of the buttons, the button stays highlighted until you click the button again (it does not open the difficulty dialog when clicking the second time, but does so the next click).

The other rolls that I tried were Skills, Beginner's Luck, Spell rolls and Armor, which all worked as expected. For Spells, the first roll (the test for whether the spell was successful) works as expected, but the roll for Tax after fails.

**To Reproduce**
Make any roll of the above types.

**Expected behavior**
Rolls as before v10.

**Screenshots**
Relationships:
![image](https://user-images.githubusercontent.com/110104157/190995871-a4a17dfc-4a57-4172-a784-247b0df57ac1.png)
Stats:
![image](https://user-images.githubusercontent.com/110104157/190996007-a149fcb0-e9dc-4750-9535-0b80f0f7fcc1.png)
Attributes:
![image](https://user-images.githubusercontent.com/110104157/190996133-a3e164e1-7d39-407b-9145-b0be2a728f86.png)
Spell Tax:
![image](https://user-images.githubusercontent.com/110104157/190996310-17236037-d060-4e75-ace9-ed97070604cb.png)
Shrug It Off/Grit Your Teeth:
(Error log)
![image](https://user-images.githubusercontent.com/110104157/191000562-d154ecd8-dbee-437f-91db-3d171fdd0b2c.png)
(Chat message working as normal)
![image](https://user-images.githubusercontent.com/110104157/191001786-d24d08c5-e03f-4675-967f-b3be1a8bc701.png)
(After making the roll)
![image](https://user-images.githubusercontent.com/110104157/191013621-9ad6a734-6c81-4003-a83a-dbb0b8c38ffd.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 1.3.0

**Additional context**
This was tested using a world created before v10 (unable to test on clean world because of #391)

**Comment by StasTserk** [comment]
@BBBNBBB Though this issue is marked as resolved, I will note that I was not able to reproduce the `shrug it off/grit your teeth` nor the `relationship` roll error text you have posted (`Cannot read properties of undefined. Reading 'indexOf'`).

Notably the line of code triggering this is 
```ts
const onlySuccessCounts = this.successOnlyRolls.indexOf(name) !== -1;
```
In this case, `successOnlyRolls` is a pre-prepared list of which rolls only give progress on successes. This should be present in every actor but seemingly in the test you performed that array is missing entirely. I have some suspicion that the issue you're dealing with is related to a bug that was present in foundry release `285` regarding unlinked token data being improperly migrated. There was just a hotfix today for this, so if you wouldn't mind verifying this isn't present in the latest version that would be great!
