### ISSUE TITLE
Forte Tax 

### ISSUE THREAD

**Issue by dmeaden** [StasTserk/foundry-burningwheel#395]
When trying to change the Tax on the Forte stat, there's no way to click it to change the value.

**Comment by StasTserk** [comment]
This is intentional as the way that forte gets taxed is via failing forte tests after spellcasting. All of the related fields
(the determining input for will tax as well) are located down in the [sorcery section of the character sheet.](https://github.com/StasTserk/foundry-burningwheel/wiki/Character-Sheet#spells)
